var main_characters = [
  'Harry Potter',
  'Ron Weasley',
  'Hermione Granger',
  'Albus Dumbledore',
  'Severus Snape',
  'Rubeus Hagrid',
  'Draco Malfoy'
]

var death_eaters = [
  'avery',
  'regulus black',
  'alecto carrow',
  'amycus carrow',
  'barty crouch jr',
  'antonin dolohov',
  'fenrir greyback',
  'igor karkaroff',
  'bellatrix lestrange',
  'walden macnair',
  'draco malfoy',
  'lucius malfoy',
  'peter pettigrew',
  'severus snape',
  'yaxley'
]

var dumbledores_army = [
  'Hannah Abbott',
  'Katie Bell',
  'Susan Bones',
  'Terry Boot',
  'Lavender Brown',
  'Cho Chang',
  'Michael Corner',
  'Colin and Dennis Creevey',
  'Marietta Edgecombe',
  'Justin Finch-Fletchley',
  'Seamus Finnigan',
  'Anthony Goldstein',
  'Angelina Johnson',
  'Lee Jordan',
  'Neville Longbottom',
  'Luna Lovegood',
  'Ernie Macmillan',
  'Padma Patil',
  'Parvati Patil',
  'Zacharias Smith',
  'Alicia Spinnet',
  'Dean Thomas',
  'Fred Weasley',
  'George Weasley',
  'Ginny Weasley'
]

var howgarts_staff = [
  'cuberth binns',
  'charity burbage',
  'alecto carrow',
  'amycus carrow',
  'albus dumbledore',
  'firenze',
  'irma pince',
  'dolores umbridge',
  'argus filch',
  'filius flitwick',
  'gilderoy lockhart',
  'minerva mcgonagall',
  'poppy pomfrey',
  'quirinus quirrel',
  'horace slughorn',
  'pomona sprout',
  'sybill trelawney'
]

var order = [
  'sirius black',
  'fleur delacour',
  'aberforth dumbledore',
  'arabella figg',
  'remus lupin',
  'alastor moody',
  'james potter',
  'lily potter',
  'kingsley shacklebolt',
  'nymphadora tonks',
  'arthur weasley',
  'bill weasley',
  'charlie weasley',
  'molly weasley'
]

var hogwarts_ghosts = [
  'bloddy baron',
  'fat friar',
  'grey lady',
  'nearly headless nick'
]

var hogwarts_founders = [
  'godric gryffindor',
  'helga hufflepuff',
  'rowena ravenclaw',
  'salazar slytherin'
]

var hogwarts_houses = [
  'gryffindor',
  'hufflepuff',
  'ravenclaw',
  'slytherin'
]

// https://en.wikipedia.org/wiki/List_of_spells_in_Harry_Potter
var spells = [
  'accio',
  'aguamenti',
  'alohomora',
  'anapneo',
  'aparecium',
  'avada kedavra',
  'avis',
  'cave inimicum',
  'colloportus',
  'confringo',
  'confundo',
  'crucio',
  'defodio',
  'deletrius',
  'densaugeo',
  'deprimo',
  'descendo',
  'diffindo',
  'duro',
  'engorgio',
  'episkey',
  'erecto',
  'evanesco',
  'expecto patronum',
  'expelliarmus',
  'expulso',
  'ferula',
  'finite incantatem',
  'flagrate',
  'furnunculus',
  'geminio',
  'glisseo',
  'impedimenta',
  'imperio',
  'impervius',
  'incendio',
  'langlock',
  'legilimens',
  'levicorpus',
  'liberacorpus',
  'locomotor',
  'locomotor mortis'
  'lumos',
  'meteolojinx recanto',
  'mobiliarbus',
  'mobilicorpus',
  'morsmordre',
  'muffliato',
  'nox',
  'obscuro',
  'oppugno',
  'orchideous',
  'petrificus totalus',
  'piertotum locomotor',
  'prior incantato',
  'protego',
  'protego horribilis',
  'protego totalum',
  'reducio',
  'reducto',
  'relashio',
  'rennervate',
  'reparo',
  'rictusempra',
  'riddikulus',
  'salvio hexia',
  'scourgify',
  'sectumsempra',
  'serpensortia',
  'silencio',
  'sonorus',
  'specialis revelio',
  'stupefy',
  'tarantallegra',
  'tergeo',
  'unbreakable vow',
  'waddiwasi',
  'wingardium leviosa'
]
